// js/dom-refs.js
// Cached references to all DOM elements used by the application.
// Populated once at startup so every module can import this object
// instead of calling getElementById repeatedly.

export const dom = {
    uploadPairsContainer:      () => document.getElementById('upload-pairs-container'),
    addPairBtn:                () => document.getElementById('add-pair-btn'),
    uploadPairTemplate:        () => document.getElementById('upload-pair-template'),
    compareBtn:                () => document.getElementById('compare-btn'),
    reportSection:             () => document.getElementById('report-section'),
    reportContent:             () => document.getElementById('report-content'),
    feedbackModal:             () => document.getElementById('feedback-modal'),
    feedbackModalTitle:        () => document.getElementById('feedback-modal-title'),
    incorrectItemDetails:      () => document.getElementById('incorrect-item-details'),
    feedbackExplanation:       () => document.getElementById('feedback-explanation'),
    cancelFeedbackBtn:         () => document.getElementById('cancel-feedback-btn'),
    submitFeedbackBtn:         () => document.getElementById('submit-feedback-btn'),
    historySection:            () => document.getElementById('history-section'),
    historySearchInput:        () => document.getElementById('history-search-input'),
    historySearchBtn:          () => document.getElementById('history-search-btn'),
    historyResults:            () => document.getElementById('history-results'),
    uploadSection:             () => document.getElementById('upload-section'),
    newComparisonBtn:          () => document.getElementById('new-comparison-btn'),
    clearHistoryBtn:           () => document.getElementById('clear-history-btn'),
    feedbackTextareaContainer: () => document.getElementById('feedback-textarea-container'),
    feedbackImageContainer:    () => document.getElementById('feedback-image-container'),
    feedbackImagePreview:      () => document.getElementById('feedback-image-preview'),
    feedbackImageDelete:       () => document.getElementById('feedback-image-delete'),
    guidelineModal:            () => document.getElementById('guideline-modal'),
    addGuidelineBtn:           () => document.getElementById('add-guideline-btn'),
    cancelGuidelineBtn:        () => document.getElementById('cancel-guideline-btn'),
    saveGuidelineBtn:          () => document.getElementById('save-guideline-btn'),
    guidelineInput:            () => document.getElementById('guideline-input'),
    guidelinesList:            () => document.getElementById('guidelines-list'),
    guidelinesHeader:          () => document.getElementById('guidelines-header'),
    guidelinesContent:         () => document.getElementById('guidelines-content'),
    fabricPropertiesHeader:    () => document.getElementById('fabric-properties-header'),
    fabricPropertiesContent:   () => document.getElementById('fabric-properties-content'),
    fabricPropertiesList:      () => document.getElementById('fabric-properties-list'),
    fabricCsvUpload:           () => document.getElementById('fabric-csv-upload'),
    fabricCsvDropZone:         () => document.getElementById('fabric-csv-drop-zone'),
    addFabricBtn:              () => document.getElementById('add-fabric-btn'),
    motorPropertiesHeader:     () => document.getElementById('motor-properties-header'),
    motorPropertiesContent:    () => document.getElementById('motor-properties-content'),
    motorPropertiesList:       () => document.getElementById('motor-properties-list'),
    motorCsvUpload:            () => document.getElementById('motor-csv-upload'),
    motorCsvDropZone:          () => document.getElementById('motor-csv-drop-zone'),
    addMotorBtn:               () => document.getElementById('add-motor-btn'),
    tubePropertiesHeader:      () => document.getElementById('tube-properties-header'),
    tubePropertiesContent:     () => document.getElementById('tube-properties-content'),
    tubePropertiesList:        () => document.getElementById('tube-properties-list'),
    tubeCsvUpload:             () => document.getElementById('tube-csv-upload'),
    tubeCsvDropZone:           () => document.getElementById('tube-csv-drop-zone'),
    addTubeBtn:                () => document.getElementById('add-tube-btn'),
    confirmModal:              () => document.getElementById('confirm-modal'),
    confirmModalTitle:         () => document.getElementById('confirm-modal-title'),
    confirmModalBody:          () => document.getElementById('confirm-modal-body'),
    confirmModalCancel:        () => document.getElementById('confirm-modal-cancel'),
    confirmModalConfirm:       () => document.getElementById('confirm-modal-confirm'),
};
